### ISSUE TITLE
Add support to generate expect tests

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-test#23]
Currently, `lsif-validate` only asserts that a given LSIF index is structurally valid (all edges point to existing vertices). It would be nice if there was a companion `lsif-expect` command that generates a directory that mirrors the source tree with inline annotations that document the navigation.

Example usage:
```ts
$ cat src/myapp.ts
import * as sourcegraph from 'sourcegraph'

export function activate(context: sourcegraph.ExtensionContext): void {
    context.subscriptions.add(
        sourcegraph.languages.registerHoverProvider(['yaml', 'json'], {})
    )
}
```
```
$ tree src
├── myapp.ts
└── mylib.ts
$ lsif-node # generates dump.lsif
$ lsif-expect # generates dump.lsif-expect
$ tree dump.lsif-expect
├── myapp.ts
└── mylib.ts
```

The generated annotations could look like this
```ts
$ cat dump.lsif-expect/myapp.ts
import * as sourcegraph from 'sourcegraph'

export function activate/*L3*/(context/*L3*/: sourcegraph/*L0*/.ExtensionContext/*sourcegraph.d.ts*/): void {
    context/*L3*/.subscriptions/*sourcegraph.d.ts*/.add/*sourcegraph.d.ts*/(
        sourcegraph/*L0/*.languages/*sourcegraph.d.ts*/.registerHoverProvider/*sourcegraph.d.ts*/(['yaml', 'json'], {})
    )
}
```

We have used a similar scheme in the test suite for Metals (scala language server) with good success https://github.com/scalameta/metals/blob/86ed213f3aebf9f86c6d8f1c7889762e78661acf/tests/unit/src/test/scala/tests/DefinitionLspSuite.scala#L61

The format of the annotations can evolve as we come up with different use-cases.

**Comment by Strum355** [comment]
First off, Im very happy this challenge is being tackled : )

What would be the best way of approaching this for validating that a given hover text for a text range is correct? Im assuming the text wouldnt be included in the annotation (that could get quite large) or is that the expected result? I know this is still an early draft so things may change completely or everything necessary hasnt been specced out yet.

Im also not sure how this would work for languages that dont have inline comments e.g. Python.

**Comment by olafurpg** [comment]
> Im also not sure how this would work for languages that dont have inline comments e.g. Python.

That's a good point. The generated code doesn't need to be executable so we can use any syntax, but it would be nice to use a format that provides usable syntax highlighting. The expect files should maybe use a custom file extension that doesn't have syntax highlighting 🤔 

> What would be the best way of approaching this for validating that a given hover text for a text range is correct?

Good question. One approach would be to format only the fact that an identifier has hover message. 
We could optionally insert some kind of identifier to the quotes that references a line at the bottom of the document. For example

```ts
$ cat dump.lsif-expect/myapp.ts.expect-hover
import * as «sourcegraph-1» from 'sourcegraph'

export function activate(context: «sourcegraph-1».«ExtensionContext-4»)...

1: sourcegraph extension API ..
2: the extension context is passed ..
```

**Comment by Strum355** [comment]
Also curious now on if its expected that lsif-expect knows the grammar for each language we support in order to add those annotations, or if theyll be purely based on the ranges output by the indexers. 

What problem do the inline annotations themselves solve specifically? Is it so we can verify with human eyes? Is it then expected to go over every input/output file to guarantee that theyre all valid?

**Comment by olafurpg** [comment]
> Also curious now on if its expected that lsif-expect knows the grammar for each language we support in order to add those annotations, or if theyll be purely based on the ranges output by the indexers.

I think it's possible to generate the annotations purely from the LSIF data.

> What problem do the inline annotations themselves solve specifically? Is it so we can verify with human eyes? Is it then expected to go over every input/output file to guarantee that theyre all valid?

Correct. The main purpose of the annotations is to make it easy to reproduce navigation bugs and to make it easy for a human to review that a change fixes the bug. Expect tests like this also help catch regressions.

**Comment by Strum355** [comment]
Sounds good to me then, I like this human-readable approach : )

**Comment by efritz** [comment]
There was an lsif-annotate command at one point that would display annotations in the line below in the terminal. Maybe that could be a possibility as well? e.g.

```
export function active(context: Context)
                ^^^^^^ ^^^^^^^  ^^^^^^^
```

Where this would somehow be tagged like in the previous examples.

**Comment by olafurpg** [comment]
@efritz I like that format! We use something similar to test the syntax highlighting rules for Scala in VS Code, example https://github.com/scala/vscode-scala-syntax/blob/bf16fd4715e31ce593cf2e9c4cd8d4859fae3e86/tests/snap/backticks.test.scala.snap

The benefit of that format is that you can maybe insert multiple layers of information on a given line, definition + hover + references
```
export function active(context: Context)
                ^^^^^^ definition
                       ^^^^^^^ definition
                                ^^^^^^^ reference, hover
```
It should remain quite readable as long as you don't cram in too many identifiers on the same line.
